- hosts: all
  gather_facts: false
  
  tasks:

    - name: Execute script on destination server
      script: fetchJavaVersion.sh
    - name: change permission
      shell: chmod 777 /tmp/wasJAVAversion.txt /tmp/wasJAVAversion.res
    - name: copy result from destination
      command: cat /tmp/wasJAVAversion.res > /tmp/Result/wasJAVAversion.txt_{{ inventory_hostname }}

    
      


