parameters:
- name: targetEnvironment
  default: Dev
  values:
  - Dev
  - Tst
  - Acc
  - Prd

trigger:
 - none

variables:
  - group: Abnamro.Coesd.VariableGroup.GlobalVars
  - group: TeamVars.MQFTE
  - group: AAI4AAB-Certificate-Management

resources:
  repositories:
    - repository: pipetemplates
      type: git
      name: GRD0001045/pita-pipeline-templates
      ref: 'refs/heads/master'

stages:
- stage: CI_Linting
  jobs:
  - template: flows/ci-ansible-onpremise.yml@pipetemplates
    parameters:
      nexus3_docker_releases_sc: 'mqfte-nx3-docker-releases-sc'
      trigger_xlr: false


- stage: COTS_CD_${{ parameters.targetEnvironment }}_KYNDRYL
  dependsOn: 
  - CI_Linting
  condition: succeeded()
  jobs:
  - template: flows/cd-ado-at.yml@pipetemplates
    parameters:
      deployment_environment: ${{ parameters.targetEnvironment }}
      target_platform: 'KYNDRYL-WAS'
      vault_password: $(ansible_vault_DEV_password)
      playbook_name: 'site'
      nexus3_docker_releases_sc: 'mqfte-nx3-docker-releases-sc'
      app_id: 'MQFTE'
      ${{ if startsWith(parameters.targetEnvironment, 'A') }}:
        approval_environment: 'MID_AAI4AAB_ACC'
        dependsOn_job: CreateETChange
      ${{ if startsWith(parameters.targetEnvironment, 'P') }}:
        approval_environment: 'MID_AAI4AAB_PRD'
        dependsOn_job: CreatePRChange
      launch_job_template: 'true'
#      job_extra_vars: '{"tokenEnvironment":"${{ parameters.tokenEnvironment }}","resourceSecret":"$(acc-resource)","clientId":"$(acc-client-id)","clientSecret":"$(acc-client-secret)"}'
#      job_extra_vars: '{"forceRenewal":"True","resourceSecret":"$(prd-resource)","clientId":"$(prd-client-id)","clientSecret":"$(prd-client-secret)","prd_data":{"resourceSecret":"$(prd-resource)","clientId":"$(prd-client-id)","clientSecret":"$(prd-client-secret)"},"acc_data":{"resourceSecret":"$(acc-resource)","clientId":"$(acc-client-id)","clientSecret":"$(acc-client-secret)"}}'
      job_extra_vars: '{"resourceSecret":"$(prd-resource)","clientId":"$(prd-client-id)","clientSecret":"$(prd-client-secret)"}'
      manual_validation_approver_email_id: |
        aai4aab@nl.abnamro.com