---
- hosts: all
  strategy: free
  #serial: 10

  #  gather_facts: false

  # set required vault_* values, if not provided from outside
  #  pre_tasks:
  #    - name: Setup the global extra's, not depending on gather facts
  #      set_fact:
  #        hostname: "{{ inventory_hostname }}"
  #        var_xtra: "{{ vault_svn_password }}"

  vars:
    token_environment: Prd
    certMinDaysValid: 30
    forceRenewal: false
    certificateReplacementSuffix: "{{ '-%Y%m%d' | strftime }}"
    backupPostfix: "{{ '%Y%m%d%H%M' | strftime }}"
    certificateWorkDir: /tmp/certificateWorkDir
    storeSecret: default
    azure_ra_email: Squad-301-WAS@kyndryl.com
    dmgr_block_id: "BLK0003832"
    dmgr_oar_id: "AAB.SYS.016416"
    sslSettings:
      dmgr: CellDefaultSSLSettings 
      #node: NodeDefaultSSLSettings

  roles:
    - role: check_privilege_role
      accounts: wasusr

  tasks:
    - name: main body
      block:
        - name: It main be a restart...
          block:
            - name: So first accept the trust... 
              include_tasks: WebsphereScripts/acceptTrust.yml
              vars:
                first_entry: True
          become: true
          become_user: wasusr
          become_method: sudo

        - name: loop through sslSettings
          include_tasks: certificateRenewalByScope.yml
          vars:
            scopeType: "{{ item.key }}"
            aliasSSLSettings: "{{ item.value }}"
          loop: "{{ sslSettings | dict2items }}"

        - name: final time to get the latest status on the certificates
          include_tasks: certificateReportByScope.yml
          vars:
            scopeType: "{{ item.key }}"
            aliasSSLSettings: "{{ item.value }}"
          loop: "{{ sslSettings | dict2items }}"
      always:
        - name: Always do this
          ansible.builtin.debug:
            msg: "This always executes"
        - name: Run me even after an error
          include_tasks: openssl/post_cleanup.yml

  handlers:
    - name: Always do this
      ansible.builtin.debug:
        msg: "This always executes as handler"
    - name: Run me even after an error
      include_tasks: openssl/post_cleanup.yml
