# default playbook, will be triggered by release_vars.yml commit
#

trigger:
  paths:
    include:
    - release_vars.yml

resources:
  repositories:
  - repository: mid-library
    type: git
    name: GRD0001078/aai4aab-mid-auth-build-library

extends:
  template: flows/aai4aab-playbook-default.yml@mid-library